spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/datart1?&allowMultiQueries=true&characterEncoding=utf-8
    username: "root"
    password: "qq123123"

server:
  port: 8081
  address: 0.0.0.0

  compression:
    enabled: true
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

datart:

  migration:
    enable: true

  server:
    address: http://127.0.0.1:8081

  user:
    active:
      send-mail: false  # 注册用户时是否需要邮件验证激活

  security:
    token:
      secret: "d@a$t%a^r&a*t" #加密密钥
      timeout-min: 30  # 登录会话有效时长，单位：分钟。

  env:
    file-path: ${user.dir}/files # 服务端文件保存位置

  screenshot:
    timeout-seconds: 60
    webdriver-type: CHROME
    webdriver-path: